# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-07 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_picture'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default=True, upload_to=users.models.upload_image_path),
        ),
    ]
