# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songplayer', '0002_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('target', models.FileField(max_length=50, upload_to='')),
                ('genre', models.CharField(max_length=15, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songplayer.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songplayer.Artist')),
            ],
        ),
    ]
