# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songplayer', '0004_auto_20180711_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='artist_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='album_id',
        ),
        migrations.RenameField(
            model_name='youtube',
            old_name='artist',
            new_name='artist_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
    ]
