# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songplayer', '0005_auto_20180711_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='target',
            field=models.FileField(max_length=500, upload_to=''),
        ),
    ]
