# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songplayer', '0006_auto_20180711_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='songplayer.Album'),
        ),
    ]
