# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-12 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songplayer', '0009_auto_20180711_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='name',
            new_name='album_name',
        ),
    ]
