# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-12 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songplayer', '0010_auto_20180712_0531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='Year',
            new_name='year',
        ),
    ]
