# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-12 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songplayer', '0012_auto_20180712_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='year',
        ),
        migrations.AddField(
            model_name='album',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
