# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-19 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import songplayer.models


class Migration(migrations.Migration):

    dependencies = [
        ('songplayer', '0013_auto_20180712_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='target',
            field=models.FileField(null=True, upload_to=songplayer.models.upload_file_path),
        ),
    ]
