# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-25 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songplayer', '0015_auto_20180719_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
