# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-09 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.EmailField(max_length=254, unique=True)),
                ('subscriber_name', models.CharField(max_length=40, null=True)),
                ('channel_secrets', models.CharField(max_length=150)),
                ('channel_type', models.IntegerField()),
            ],
        ),
    ]
